/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package filehub;

import com.teamdev.services.App;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {

    @Test
    void appHasAGreeting() {
        assertNotNull(App.getGreeting(), "app should have a greeting");
    }
}
