/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.teamdev.persistent;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static String getGreeting() {

        if (logger.isInfoEnabled()) {
            logger.info("[Greeting requested]");
        }

        return "Hello World!";
    }

    public static void main(String[] args) {

        if (logger.isInfoEnabled()) {
            logger.info("[App started]");
        }

    }
}
