/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.teamdev.persistent;

public class App {

    public static String getGreeting() {

        return "Hello World!";
    }

    public static void main(String[] args) {

    }
}
