/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.teamdev.services;

import com.google.common.flogger.FluentLogger;

public class App {

    private static final FluentLogger logger = FluentLogger.forEnclosingClass();

    public static String getGreeting() {

        logger.atInfo()
              .log("[Logging message in greeting]");

        return "Hello World!";
    }

    public static void main(String[] args) {
        logger.atInfo()
              .log("[Logging message in main]");
    }
}
